-dontoptimize
-dontobfuscate
-keep class kotlin.** { *; }
-keep class androidx.tracing.** { *; }
-keep class androidx.compose.runtime.** { *; }
-keep class com.google.android.play.core.splitcompat.** { *; }
-keep class com.simtop.beer_data.di.** { *; }
-keep class com.simtop.beer_database.di.** { *; }
-keep class com.simtop.beer_network.di.** { *; }
-keep class com.simtop.billionbeers.di.** { *; }
-keep class com.simtop.core.di.** { *; }
-keep class com.simtop.billionbeers.BillionBeersApplication { *; }
-keep interface com.simtop.core.di.GraphProvider
-keep class dev.zacsweers.metro.** { *; }
-keep class dev.zacsweers.metrox.** { *; }
