import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val org_jetbrains_kotlinx_kotlinx_coroutines: String = "1.3.9"

    const val androidx_test_espresso: String = "3.3.0"

    const val com_squareup_okhttp3: String = "4.8.1"

    const val org_jetbrains_kotlin: String = "1.4.0"

    const val androidx_navigation: String = "2.3.0"

    const val com_google_dagger: String = "2.28.3"

    const val androidx_room: String = "2.2.5"

    const val androidx_test: String = "1.3.0"

    const val io_mockk: String = "1.10.0"

    const val com_android_tools_build_gradle: String = "4.0.1"

    const val androidx_core_core_ktx: String = "1.3.1"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.7.0"

    const val lifecycle_extensions: String = "2.2.0"

    const val constraintlayout: String = "2.0.1"

    const val fragment_testing: String = "1.2.5"

    const val converter_gson: String = "2.9.0"

    const val core_testing: String = "2.1.0"

    const val lint_gradle: String = "27.0.1"

    const val viewbinding: String = "4.0.1"

    const val appcompat: String = "1.2.0"

    const val junit_ktx: String = "1.1.2"

    const val material: String = "1.2.1"

    const val kluent: String = "1.61"

    const val aapt2: String = "4.0.1-6197926"

    const val glide: String = "4.11.0"

    const val junit: String = "4.13"

    /**
     * Current version: "6.1.1"
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "6.6.1"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
